#!/bin/sh

if [ -z "${ONE_DRIVE_PATH}" ]; then
	echo "no env var: ONE_DRIVE_PATH" >/&2
	exit 1
fi

mkdir -p ~/.ssh

scp -vr fedora:/root/.ssh ~/
rm -f ~/.ssh/known_hosts
cp -vr ~/.ssh/* "${ONE_DRIVE_PATH}/文档/ssh-keys"

