#!/bin/bash

function update {
	bash ${MY_SCRIPT_ROOT}/install_environment.sh
	unset LINUX_TOOLBOX_INITED
	source /etc/profile.d/01-linux-toolbox.sh
}











case $1 in
update)
	update
;;
upgrade)

;;
*)
	echo "Usage: linux-toolbox <command>"
	echo " Commands:"
	echo "    update           refresh linux-toolbox install"
	echo "    upgrade          update version of linux-toolbox"
	return 1
;;
esac
