#!/bin/bash
if [ -z "${PROXY_HOST}" ]; then
	export PROXY_HOST="${SSH_CLIENT_IP-localhost}:7070"
fi
export NO_PROXY="${NO_PROXY},127.0.0.1,192.168.*,10.*,*.cn"

enable_bash(){
	export HTTP_PROXY="http://${PROXY_HOST}"
	export HTTPS_PROXY="http://${PROXY_HOST}"
}
disable_bash(){
	export HTTP_PROXY=""
	export HTTPS_PROXY=""
}

enable_npm(){
	npm config set proxy "http://${PROXY_HOST}"
	npm config set https-proxy "http://${PROXY_HOST}"
}
disable_npm(){
	npm config delete proxy
	npm config delete https-proxy
}

enable_dnf(){
	# TODO "start dnf"
}
disable_dnf(){
	# TODO "dis dnf"
}

enable_git(){
	git config --system --add global.proxy "http://${PROXY_HOST}"
}
disable_git(){
	git config --system --unset-all global.proxy
}

start_bash(){
	export PROXY_BASH=true
	echo "[entering proxy bash]" >&2
	bash
	echo "[leaving proxy bash]" >&2
}

if [ "$*" = "on" ]; then
	if [ -n "$PROXY_BASH" ]; then
		echo "you are already in proxy bash" >&2
		return 2
	fi
	echo "proxy set to ON. (PROXY=${PROXY_HOST})"
	enable_bash
	enable_npm
	enable_dnf
	enable_git
elif [ "$*" = "bash" ]; then
	enable_bash
	start_bash
	disable_bash
elif [ "$*" = "off" ]; then
	if [ -n "$PROXY_BASH" ]; then
		echo "you are already in proxy bash" >&2
		return 2
	fi
	echo "proxy set to OFF." >&2
	disable_bash
	disable_npm
	disable_dnf
	disable_git
else
	echo -e "Usage: proxy [on|off]" >&2
	return 1
fi

