#!/bin/bash

if [[ -z "$PROXY" ]]; then
	echo "environment variable PROXY is not set.">&2
	exit 1
fi
if [ "$*" = "on" ]; then
	export https_proxy=${PROXY} http_proxy=${PROXY} all_proxy=${PROXY} HTTPS_PROXY=${PROXY} HTTP_PROXY=${PROXY} ALL_PROXY=${PROXY}

	PROXY_ARGS="--proxy=${PROXY}"
	alias pip="pip ${PROXY_ARGS}"
	alias pip2="pip2 ${PROXY_ARGS}"
	alias pip3="pip3 ${PROXY_ARGS}"
	git config --system --add global.proxy "http://${PROXY_HOST}"
	unset PROXY_ARGS

	echo "Using proxy server $PROXY." >&2
elif [ "$*" = "off" ]; then
	unset https_proxy http_proxy all_proxy HTTPS_PROXY HTTP_PROXY ALL_PROXY

	unalias pip
	unalias pip2
	unalias pip3
	git config --system --unset-all global.proxy

	echo "Proxy server unset." >&2
else
	echo -e "proxy is currentlly " >&2
	echo -e "Usage: proxy [on|off]" >&2
fi

