#!/bin/bash

if [[ -z "$PROXY" ]]; then
	echo "environment variable PROXY is not set.">&2
	exit 1
fi

enable_bash(){
	export http_proxy="${PROXY_HOST}"
	export https_proxy="${PROXY_HOST}"
}
disable_bash(){
	export http_proxy=""
	export https_proxy=""
}

enable_npm(){
	npm config set proxy "http://${PROXY_HOST}"
	npm config set https-proxy "http://${PROXY_HOST}"
}
disable_npm(){
	npm config delete proxy
	npm config delete https-proxy
}

enable_dnf(){
	# TODO "start dnf"
	echo -n ""
}
disable_dnf(){
	# TODO "dis dnf"
	echo -n ""
}

enable_git(){
	git config --system --add global.proxy "http://${PROXY_HOST}"
}
disable_git(){
	git config --system --unset-all global.proxy
}

start_bash(){
	export PROXY_BASH=true
	echo "[entering proxy bash]" >&2
	bash
	echo "[leaving proxy bash]" >&2
}

if [ "$*" = "on" ]; then
	if [ -n "$PROXY_BASH" ]; then
		echo "you are already in proxy bash" >&2
		return 2
	fi
	echo "proxy set to ON. (PROXY=${PROXY_HOST})"
	enable_bash
	enable_npm
	enable_dnf
	enable_git
elif [ "$*" = "bash" ]; then
	enable_bash
	start_bash
	disable_bash
elif [ "$*" = "off" ]; then
	if [ -n "$PROXY_BASH" ]; then
		echo "you are already in proxy bash" >&2
		return 2
	fi
	echo "proxy set to OFF." >&2
	disable_bash
	disable_npm
	disable_dnf
	disable_git
else
	echo -e "Usage: proxy [on|off]" >&2
	return 1
fi

